### PR TITLE
Main Screen tabs

### PR DESCRIPTION
**Pull request by shekohex**

### CODE REVIEW

**Comment by goozang-records** [comment]
I'm getting this error right now when I try to demo it with the ios instructions. 

```
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after thei<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#6a1f8 NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#12479] ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#c9a61 ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.bottomNavigationBar
```

I'm pretty sure it's basically saying that the bottom bar needs to have some size constraints added to it in order to render correctly in ios.

Now, I'm getting this error with the following stack trace. I think it's indicating that the padding is off...

```
 The relevant error-causing widget was:
flutter:   Container file:///Users/4meta5/flutter-bin/sunshine-flutter/lib/screens/main/main_screen.dart:67:28
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new RenderPadding (package:flutter/src/rendering/shifted_box.dart:107:15)
flutter: #3      Padding.createRenderObject (package:flutter/src/widgets/basic.dart:1630:12)
flutter: #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5370:28)
flutter: #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5833:11)
flutter: ...     Normal element mounting (22 frames)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
flutter: #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
flutter: ...     Normal element mounting (102 frames)
flutter: #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
flutter: #131    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
flutter: ...     Normal element mounting (119 frames)
flutter: #250    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
flutter: #251    Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
flutter: #252    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5584:32)
flutter: #253    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5961:17)
flutter: #254    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
flutter: #257    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #258    StatefulElement.update (package:flutter/src/widgets/framework.dart:4711:5)
flutter: #259    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #261    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #262    ProxyElement.update (package:flutter/src/widgets/framework.dart:4866:5)
flutter: #263    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
flutter: #264    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #265    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
flutter: #266    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #268    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
flutter: #269    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #270    StatefulElement.update (package:flutter/src/widgets/framework.dart:4711:5)
flutter: #271    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #272    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
flutter: #273    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #274    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5841:14)
flutter: #275    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #277    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #278    StatelessElement.update (package:flutter/src/widgets/framework.dart:4587:5)
flutter: #279    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
flutter: #280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
flutter: #281    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
flutter: #282    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
flutter: #283    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #284    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
flutter: #285    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #286    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
flutter: #287    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
flutter: #288    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
flutter: #292    _invoke (dart:ui/hooks.dart:277:10)
flutter: #293    _drawFrame (dart:ui/hooks.dart:235:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Each child must be laid out exactly once.
flutter: Another exception was thrown: Updated layout information required for RenderErrorBox#57ff7 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
```

**Comment by goozang-records** [comment]
After upgrading to this version

```
➜  sunshine-flutter git:(ui) ✗ flutter --version
Flutter 1.19.0-2.0.pre.131 • channel master •
https://github.com/flutter/flutter.git
Framework • revision 478d4c9c1a (15 hours ago) • 2020-05-19 20:22:01 -0700
Engine • revision 2d4e83921d
Tools • Dart 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)
```

Here is the most recent error. I'm pretty sure there is something off with the padding.

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Container(bg: Color(0xffd7dae1)):
flutter: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 107 pos 15:
flutter: 'padding.isNonNegative': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   Container file:///Users/4meta5/flutter-bin/sunshine-flutter/lib/screens/main/main_screen.dart:67:28
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new RenderPadding (package:flutter/src/rendering/shifted_box.dart:107:15)
flutter: #3      Padding.createRenderObject (package:flutter/src/widgets/basic.dart:1631:12)
flutter: #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5375:28)
flutter: #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5838:11)
flutter: ...     Normal element mounting (22 frames)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
flutter: #28     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5956:32)
flutter: ...     Normal element mounting (102 frames)
flutter: #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
flutter: #131    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5956:32)
flutter: ...     Normal element mounting (119 frames)
flutter: #250    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3455:14)
flutter: #251    Element.updateChild (package:flutter/src/widgets/framework.dart:3223:18)
flutter: #252    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5589:32)
flutter: #253    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5966:17)
flutter: #254    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
flutter: #256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
flutter: #257    Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #258    StatefulElement.update (package:flutter/src/widgets/framework.dart:4716:5)
flutter: #259    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
flutter: #261    Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #262    ProxyElement.update (package:flutter/src/widgets/framework.dart:4871:5)
flutter: #263    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:181:11)
flutter: #264    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #265    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
flutter: #266    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #267    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
flutter: #268    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
flutter: #269    Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #270    StatefulElement.update (package:flutter/src/widgets/framework.dart:4716:5)
flutter: #271    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #272    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
flutter: #273    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #274    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5846:14)
flutter: #275    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #276    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
flutter: #277    Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #278    StatelessElement.update (package:flutter/src/widgets/framework.dart:4592:5)
flutter: #279    Element.updateChild (package:flutter/src/widgets/framework.dart:3210:15)
flutter: #280    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4536:16)
flutter: #281    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4684:11)
flutter: #282    Element.rebuild (package:flutter/src/widgets/framework.dart:4227:5)
flutter: #283    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2632:33)
flutter: #284    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
flutter: #285    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #286    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #287    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #288    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #292    _invoke (dart:ui/hooks.dart:267:10)
flutter: #293    _drawFrame (dart:ui/hooks.dart:225:3)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: Each child must be laid out exactly once.
flutter: Another exception was thrown: Updated layout information required for RenderErrorBox#c55fc NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#c55fc NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#6225f] ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#5eb4c ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.bottomNavigationBar
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after thei<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#c55fc NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#6225f] ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#5eb4c ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.bottomNavigationBar
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after thei<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#c55fc NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#6225f] ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#5eb4c ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.bottomNavigationBar
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after thei<…>
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Cannot hit test a render box that has never been laid out.
The hitTest() method was called on this RenderBox: RenderErrorBox#c55fc NEEDS-LAYOUT NEEDS-PAINT:
  creator: ErrorWidget-[#6225f] ← Container ← MediaQuery ← LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#5eb4c ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.bottomNavigationBar
  constraints: MISSING
  size: MISSING
Unfortunately, this object's geometry is not known at this time, probably because it has never been laid out. This means it cannot be accurately hit-tested.
If you are trying to perform a hit test during the layout phase itself, make sure you only hit test nodes that have completed layout (e.g. the node's children, after thei<…>
```

**Comment by shekohex** [comment]
Could you please provide the device you are using? I'm using iPhone 11 Pro (simulator) here
image

**Comment by goozang-records** [comment]
Thanks, it was weird -- a rendering error on iPhone 8 Simulators in particular. Does this mean our code only works for iphone 11's and not iphone 8's?

**Review by goozang-records — APPROVED** [review]
Works with iPhone 11 Simulator!

**Comment by shekohex** [comment]
> Thanks, it was weird -- a rendering error on iPhone 8 Simulators in particular. Does this mean our code only works for iphone 11's and not iphone 8's?

well, I'm trying to run it on iPhone 8 (which means small screens) and fix it

**Comment by shekohex** [comment]
Fixed :)
the issue was here at 
https://github.com/sunshine-protocol/sunshine-flutter/blob/e5aa5dd0025bbe796103d0b96e56b1a5f9367427/lib/screens/main/main_screen.dart#L70

`ScreenUtil.bottomBarHeight` is zero on phones that has no bottom bars.
the last commit should fix it, and here it works fine 👍 
image

**Pull request merged**
